<template>
    <Transition
        enter-active-class="transition-[opacity]"
        leave-active-class="transition-[opacity]"
        enter-from-class="opacity-0"
        leave-to-class="opacity-0"
    >
        <slot></slot>
    </Transition>
</template>
