import type { EruditLanguageCode } from '@erudit-js/core/eruditConfig/language';

export type LanguageCode = EruditLanguageCode;
export type LanguagePhraseKey = keyof LanguagePhrases;
export type LanguagePhraseValue = string | ((...args: any[]) => string);
export type PayloadLanguagePhraseValue =
    | { type: 'missing' }
    | { type: 'string'; value: string }
    | { type: 'function'; value: string };

export type LanguagePhrases = Phrases<{
    language_code: string;
    language_name: string;
    erudit: string;
    modern_textbook: string;
    content_nav: string;
    pages: string;
    search: string;
    languages: string;
    settings: string;
    theme: string;
    theme_light: string;
    theme_dark: string;
    theme_system: string;
    built: string;
    content: string;
    add_translation: string;
    main_page: string;
    contributors: string;
    sponsors: string;
    search_the_site: string;
    searching_more: string;
    no_results: string;
    no_more_results: string;
    no_content: string;
    to_index: string;
    about_textbook: string;
    flag_title_dev: string;
    flag_hint_dev: string;
    flag_title_advanced: string;
    flag_hint_advanced: string;
    flag_title_secondary: string;
    flag_hint_secondary: string;
    ads_replacer: string;
    direct_link: string;
    direct_link_explain: string;
    book: string;
    group: string;
    topic: string;
    article: string;
    summary: string;
    practice: string;
    page: string;
    preview_content_page_description: string;
    begin_learning: string;
    flag_dev: string;
    flag_dev_description: string;
    flag_advanced: string;
    flag_advanced_description: string;
    flag_secondary: string;
    flag_secondary_description: string;
    key_elements: string;
    element_stats: string;

    // _language_title: string;
    // _language_code: string;
    // site_info_title: string;
    // site_info_slogan: string;
    // seo_index_title: string;
    // seo_index_description: string;
    // seo_article_description: (contentTitle: string) => string;
    // seo_summary_description: (contentTitle: string) => string;
    // seo_practice_description: (contentTitle: string) => string;
    // index: string;
    // pages: string;
    // search: string;
    // language: string;
    // other: string;
    // ads_replacer: string;
    // theme: string;
    // theme_system: string;
    // theme_light: string;
    // theme_dark: string;
    // content: string;
    // main_page: string;
    // contributors: string;
    // contributors_page_description: string;
    // contributors_page_invite: string;
    // become_contributor: string;
    // contributor: string;
    // contribution: string;
    // contributions_explain: (count: number) => string;
    // contributor_description: (name: string) => string;
    // editor: string;
    // add_translation: string;
    // empty_nav: string;
    // flag_dev: string;
    // flag_dev_description: string;
    // flag_advanced: string;
    // flag_advanced_description: string;
    // flag_secondary: string;
    // flag_secondary_description: string;
    // popover_dependencies: string;
    // popover_dependencies_description: string;
    // close: string;
    // back: string;
    // goto: string;
    // error: string;
    // external_link: string;
    // external_link_warn: string;
    // internal_link: string;
    // internal_link_warn: string;
    // book: string;
    // group: string;
    // topic: string;
    // topics: string;
    // article: string;
    // summary: string;
    // practice: string;
    // element_id: string;
    // preview_missing_title: string;
    // preview_missing_explain: string;
    // preview_missing_explain_mismatch: string;
    // preview_hash_mismatch_title: string;
    // preview_hash_mismatch_explain: string;
    // current_page_hash: string;
    // expected_page_hash: string;
    // empty_toc: string;
    // no_contributors: string;
    // make_contribution: string;
    // material_improvement: string;
    // how_to_improve: string;
    // edit_page: string;
    // report_problem: string;
    // references: string;
    // reference_source_featured: string;
    // references_description: string;
    // sponsors: string;
    // sponsors_description: string;
    // become_sponsor: string;
    // toc: string;
    // mentions: (conte: number) => string;
    // start_learning: string;
    // x_contributors: (count: number) => string;
    // x_sponsors: (count: number) => string;
    // show_all: string;
}>;

//
// Utility types for type safety
//

type Phrases<T extends Record<string, LanguagePhraseValue>> = T;
