import { consola } from 'consola';
import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';

interface PrepareData {
    projectPath: string;
    eruditPath: string;
    //
    contentTargets?: string | string[];
}

export async function prepare({
    projectPath,
    eruditPath,
    contentTargets,
}: PrepareData) {
    const eruditBuildDir = `${projectPath}/.erudit`;
    const distDir = `${projectPath}/.output`;

    consola.start('Cleaning up...');

    if (existsSync(distDir)) rmSync(distDir, { recursive: true });

    if (existsSync(eruditBuildDir)) rmSync(eruditBuildDir, { recursive: true });

    consola.success('Cleaned up!');

    consola.start('Generating Erudit build files...');

    mkdirSync(eruditBuildDir, { recursive: true });
    mkdirSync(eruditBuildDir + '/nuxt', { recursive: true });

    writeFileSync(
        `${eruditBuildDir}/nuxt/nuxt.config.ts`,
        `
        export default {
            compatibilityDate: '2025-07-20',
            extends: ['${eruditPath}'],
        }
        `,
    );

    ['app', 'server', 'shared', 'node'].forEach((name) => {
        writeFileSync(
            `${eruditBuildDir}/tsconfig.nuxt.${name}.json`,
            JSON.stringify(
                { extends: [`./nuxt/.nuxt/tsconfig.${name}.json`] },
                null,
                4,
            ),
        );
    });

    mkdirSync(`${eruditBuildDir}/types`, { recursive: true });

    writeFileSync(
        `${eruditBuildDir}/tsconfig.erudit.json`,
        JSON.stringify(
            {
                compilerOptions: {
                    paths: {
                        '#project/*': [`${projectPath}/*`],
                        '#content/*': [`${projectPath}/content/*`],
                    },
                    verbatimModuleSyntax: true,
                    forceConsistentCasingInFileNames: true,
                    strict: true,
                    noEmit: true,
                    skipLibCheck: true,
                    target: 'ESNext',
                    module: 'ESNext',
                    moduleResolution: 'Bundler',
                    allowJs: true,
                    resolveJsonModule: true,
                    allowSyntheticDefaultImports: true,
                    jsx: 'react-jsx',
                    jsxImportSource: '@erudit-js/prose',
                    types: ['vite/client'],
                },
                include: [`${projectPath}/**/*`, `${eruditBuildDir}/**/*`],
                exclude: [`${eruditBuildDir}/nuxt/**/*`],
            },
            null,
            4,
        ),
    );

    if (!existsSync(`${projectPath}/tsconfig.json`)) {
        writeFileSync(
            `${projectPath}/tsconfig.json`,
            JSON.stringify(
                {
                    files: [],
                    references: [
                        {
                            path: `${eruditBuildDir}/tsconfig.erudit.json`,
                        },
                        {
                            path: `${eruditBuildDir}/tsconfig.nuxt.app.json`,
                        },
                        {
                            path: `${eruditBuildDir}/tsconfig.nuxt.server.json`,
                        },
                        {
                            path: `${eruditBuildDir}/tsconfig.nuxt.shared.json`,
                        },
                        {
                            path: `${eruditBuildDir}/tsconfig.nuxt.node.json`,
                        },
                    ],
                },
                null,
                4,
            ),
        );
    }

    await prepareContentTargets(eruditBuildDir, contentTargets);

    writeFileSync(
        `${eruditBuildDir}/__AUTOGENERATED__`,
        `This directory is autogenerated by Erudit CLI.\nAll changes will be lost on next launch!`,
    );

    consola.success('Erudit build files ready!');
}

async function prepareContentTargets(
    buildDir: string,
    targets?: string | string[],
) {
    if (typeof targets === 'undefined' || targets === '') {
        return;
    }

    if (typeof targets === 'string') {
        targets = [targets];
    }

    if (Array.isArray(targets)) {
        writeFileSync(
            `${buildDir}/targets.json`,
            JSON.stringify(targets, null, 4),
        );
        consola.success(`Saved ${targets.length} content targets!`);
        return;
    }

    throw new Error(`Failed to resolve content targets: "${targets}"!`);
}
